### ISSUE TITLE
Remove firewall-policy-controller configuration

### ISSUE THREAD

**Issue by majst01** [metal-stack/gardener-extension-provider-metal#108]
Once alle firewalls in production are up to date, we should remove all remaining configuration for the deprecated firewall-policy-controller

**Comment by Gerrit91** [comment]
This needs a special mention in our release notes when we do this.

**Comment by majst01** [comment]
Is this already done ?, if yes please close

**Comment by Gerrit91** [comment]
If this is only about removing the configuration for the old firewall-policy-controller, then yes, I removed this here: https://github.com/metal-stack/gardener-extension-provider-metal/pull/166.

But I did not remove any network policies whatsoever because it was not directly obvious if belong to the firewall-policy-controller or if they are required.

**Comment by majst01** [comment]
But then we should close this and create a new issue for network policy review and potential deletion
